"""added additional one to many relationship between comments and tickets

Revision ID: 902075981e73
Revises: 0aa7ee754b5f
Create Date: 2023-10-04 19:58:54.811701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902075981e73'
down_revision = '0aa7ee754b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_ticket_id_tickets'), 'tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_ticket_id_tickets'), type_='foreignkey')
        batch_op.drop_column('ticket_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
